### ISSUE TITLE
Validate version on Dockerhub

### ISSUE THREAD

**Issue by MiniJo** [e2fyi/minio-web#5]
Hello, 

Would you mind validating the version of the "latest" image on Dockerhub?

From what I can tell, it may be 0.2.5, as I am getting the following, when trying to list folders:
```
ERR msg=Serve[/] [500]: http: wrote more than the declared Content-Length
```
This should be fixed in 0.2.6, is it possible to get that deployed ?

Thank you in advance!

**Comment by PseudoResonance** [comment]
I've created PR #7 to automatically push images to GHCR on release. I've got the latest v0.2.6 [here](https://github.com/PseudoResonance/minio-web/pkgs/container/minio-web) if anyone wants it, but you can always use the action to build your own image.

**Comment by eterna2** [comment]
Sorry for the late response. Wasn't checking my mail for sometime.

Dockerhub have removed the free tier for automated push sometime back. 

So now u can only get it from [Quay](https://quay.io/repository/e2fyi/minio-web?tab=tags). 

But thanks to @PseudoResonance, it will be available in Github registry itself.

**Comment by eterna2** [comment]
https://github.com/e2fyi/minio-web/pkgs/container/minio-web
